# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmat_test.Performer')),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='radio_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmat_test.RadioStation'),
        ),
        migrations.AddField(
            model_name='play',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmat_test.Song'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('name', 'performer')]),
        ),
    ]
