# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmat_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('title', 'performer')]),
        ),
    ]
