# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmat_test', '0002_auto_20170121_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='radiostation',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='play',
            unique_together=set([('song', 'radio_station', 'start')]),
        ),
    ]
